<?php
require_once("assets/includes/header.php");
require_once("assets/includes/classes/user.php");
$api_id = "rzp_test_1B34TLgK3agGBj";
if(!User::isLoggedIn()) {
    header("Location: signIn.php");
}
if(isset($_GET["username"])) {
    $profileUsername = $_GET["username"];
}
else {
    echo "Channel not found";
    exit();
}?>
<script>
window.addEventListener('load', function() {
    var submitButton = document.querySelector('.razorpay-payment-button');
    if (submitButton) {
      submitButton.click();
    }
  });
</script>
<?php
$username = $_GET['username'];
$amount = $_POST['addBalance'];

$user = new user($con, $username);


?>

<form action="profile.php?username=<?php echo $username; ?>" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_1B34TLgK3agGBj" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $amount*100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    // Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="ShopART"
    data-description="Add <?php echo $amount; ?>to your Wallet"
    data-image="assets/images/icons/logo2.png"
    data-prefill.name="<?php echo $username; ?>"
    data-prefill.email="<?php echo $user->getEmail();?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" value ="<?php echo $amount; ?>" custom="Hidden Element" name="hidden"/>
</form>

